[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Netlify's default Node version may differ from your local machine.
  # If you need a specific Node.js version change this value or add a .nvmrc.
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
